# Generated by Django 5.2.1 on 2025-05-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_panelist',
            field=models.BooleanField(default=True),
        ),
    ]
