# Generated by Django 5.2.1 on 2025-05-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_panelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='points_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
